window:
    padding:
     x: 5
     y: 5

    dynamic_padding: true

    opacity: 1.0

    title: Alacritty

    dynamic_title: true

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 11.0 
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
draw_bold_text_with_bright_colors: true

#selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  #semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  #save_to_clipboard: false

cursor:
  style:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: underline
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: On
    blink_interval: 750
    blink_timeout: 5
    unfocused_hollow: true
    thickness: 0.15

live_config_reload: true

shell:
  program: /bin/zsh
# BEGIN ACE
colors:
  primary:
    background: '#1d1c1c'
    foreground: '#e8d1db'
  cursor:
    text:       '#1d1c1c'
    cursor:     '#e8d1db'
  normal:
    black:      '#1d1c1c'
    red:        '#CA7D82'
    green:      '#A594A1'
    yellow:     '#AAA9BB'
    blue:       '#C694A0'
    magenta:    '#BAAFC6'
    cyan:       '#C5B7CE'
    white:      '#e8d1db'
  bright:
    black:      '#a29299'
    red:        '#CA7D82'
    green:      '#A594A1'
    yellow:     '#AAA9BB'
    blue:       '#C694A0'
    magenta:    '#BAAFC6'
    cyan:       '#C5B7CE'
    white:      '#e8d1db'
# END ACE
