#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
$HOME/.screenlayout/pantallas.sh &

bspc wm -O HDMI-A-0 eDP

bspc monitor HDMI-A-0 -d 1 2 3 4 5
bspc monitor eDP -d 6 7 8 9 0
bspc config border_width 0
bspc config window_gap 30

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a zoom state=floating

$HOME/.scripts/launch.sh
