#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

INTERNAL_MONITOR="eDP"
EXTERNAL_MONITOR="HDMI-A-0"
# on first load setup default workspaces
if [[ "$1" = 0 ]]; then
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5
		bspc monitor "$EXTERNAL_MONITOR" -d 6 7 8 9 10
		bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
	else
		bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
	fi
fi

monitor_add() {
	# Move first 5 desktops to external monitor
	for desktop in $(bspc query -D --names -m "$INTERNAL_MONITOR" | sed 5q); do
		bspc desktop "$desktop" --to-monitor "$EXTERNAL_MONITOR"
	done

	# Remove default desktop created by bspwm
	bspc desktop Desktop --remove

	# reorder monitors
	bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
}

monitor_remove() {
	# Add default temp desktop because a minimum of one desktop is required per monitor
	bspc monitor "$EXTERNAL_MONITOR" -a Desktop

	# Move all desktops except the last default desktop to internal monitor
	for desktop in $(bspc query -D -m "$EXTERNAL_MONITOR"); do
		bspc desktop "$desktop" --to-monitor "$INTERNAL_MONITOR"
	done

	# delete default desktops
	bspc desktop Desktop --remove

	# reorder desktops
	bspc monitor "$INTERNAL_MONITOR" -o 1 2 3 4 5 6 7 8 9 10
}

if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
	# set xrandr rules for docked setup
	xrandr --output "$INTERNAL_MONITOR" --mode 1920x1080 --output "$EXTERNAL_MONITOR" --primary --mode 1920x1080
	if [[ $(bspc query -D -m "${EXTERNAL_MONITOR}" | wc -l) -ne 5 ]]; then
		monitor_add
	fi
	bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
else
	# set xrandr rules for mobile setup
	xrandr --output "$INTERNAL_MONITOR" --primary --mode 1920x1080 --output "$EXTERNAL_MONITOR" --off
	if [[ $(bspc query -D -m "${INTERNAL_MONITOR}" | wc -l) -ne 10 ]]; then
		monitor_remove
	fi
fi

bspc config border_width 2
bspc config window_gap 30
bspc config border_radius 10
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc rule -a Lxappearance state=floating
bspc rule -a Arandr state=floating
bspc rule -a zoom state=floating center=on follow=on border=off

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

#bspc config normal_border_color "$color10"
#bspc config active_border_color "$color2"

bspc config focused_border_color "$color4"

bspc config presel_feedback_color "$color1"

$HOME/.scripts/screen/wal-script.sh
$HOME/.scripts/launch.sh
